# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a56d5efd4d9684a5df37291514fe53bb0ce513dc7ac924b68634579c7232afbb82007c6965c08937be61838c0b94ec06f78c0f96a3c5cf27236616bba4e4ccc

test:
  secret_key_base: 3f8dfe8757f0cf4a88794d47dd27dcd030bfee67b846babf3897994643b4b2a941382eb691c6dfa817e705d275551597e99ef5801131601e5b7fe91ef3bad3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
